from distutils.core import setup

setup(
    name='Python',
    version='',
    packages=['PythonExo.lib.python3.6.distutils', 'PythonExo.lib.python3.6.encodings',
              'PythonExo.lib.python3.6.importlib', 'PythonExo.lib.python3.6.collections',
              'PythonExo.lib.python3.6.site-packages.pip', 'PythonExo.lib.python3.6.site-packages.pip.req',
              'PythonExo.lib.python3.6.site-packages.pip.vcs', 'PythonExo.lib.python3.6.site-packages.pip.utils',
              'PythonExo.lib.python3.6.site-packages.pip.compat', 'PythonExo.lib.python3.6.site-packages.pip.models',
              'PythonExo.lib.python3.6.site-packages.pip._vendor',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.distlib',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.colorama',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.trie',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.serializer',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.lockfile',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.progress',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.chardet',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.util',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.packaging',
              'PythonExo.lib.python3.6.site-packages.pip._vendor._markerlib',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'PythonExo.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'PythonExo.lib.python3.6.site-packages.pip.commands',
              'PythonExo.lib.python3.6.site-packages.pip.operations', 'PythonExo.lib.python3.6.site-packages.wheel',
              'PythonExo.lib.python3.6.site-packages.wheel.test',
              'PythonExo.lib.python3.6.site-packages.wheel.test.simple.dist.simpledist',
              'PythonExo.lib.python3.6.site-packages.wheel.test.complex-dist.complexdist',
              'PythonExo.lib.python3.6.site-packages.wheel.tool',
              'PythonExo.lib.python3.6.site-packages.wheel.signatures',
              'PythonExo.lib.python3.6.site-packages._markerlib', 'PythonExo.lib.python3.6.site-packages.setuptools',
              'PythonExo.lib.python3.6.site-packages.setuptools.command',
              'PythonExo.lib.python3.6.site-packages.pkg_resources',
              'PythonExo.lib.python3.6.site-packages.pkg_resources._vendor',
              'PythonExo.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='ghadhakanka',
    author_email='',
    description=''
)
